### ISSUE TITLE
rpyutils directory missing after install

### ISSUE THREAD

**Issue by andurin** [rpp0/scapy-fakeap#3]
Hi,

after a python setup.py install your subdirectory rpyutils is missing.

I'm not yet familar with python setuptools to send you a patch right now.
Guess you are faster then I :)

Regards
Andurin

**Comment by rpp0** [comment]
Hi,

Thanks for identifying this issue! I will take a look at it later today :)

**Comment by rpp0** [comment]
Ok, I updated the file. Does install work for you now?

**Comment by andurin** [comment]
install is fine now. Thanks for fast investigation.

**Comment by rpp0** [comment]
Thank you for reporting and for your interest in scapy-fakeap! Actually I should clean up my code since I think it's a bit messy, but I don't have a lot of spare time right now unfortunately.
