### ISSUE TITLE
got a question..

### ISSUE THREAD

**Issue by localtracker** [rpp0/scapy-fakeap#4]
Hey there,
Is the AP that is created under the scapy TCP/IP stack or the Native TCP/IP stack? If it is under the scapy stack then how can I reject packets to the AP? And if it is not, is there a way to create an AP under python which can be integrated with the native tcp/ip stack and can reject packets acting like a traditional firewall?

**Comment by rpp0** [comment]
In scapy-fakeap, the layers above the TCP layer of a frame are not dissected further in Scapy. Instead, such frames are forwarded to the "fakeap" virtual interface, where they can be processed by any application. You could use iptables to reject certain packets in this case. Note that despite this optimisation, in my experience using Scapy for processing the higher layers is still pretty slow.

**Comment by localtracker** [comment]
thanks for the reply. How would the iptables rules be if I were to detect and remove deauth packets? I think you're getting the direction I wanna go in. Would I still be able to use scapy to create and implement these rules to the 'fakeap' iface?

**Comment by rpp0** [comment]
Lower layers are not forwarded to the fakeap interface, so for filtering deauth packets you can use the BPF filter argument in the constructor of the AP.

**Comment by localtracker** [comment]
if i try 
ap = FakeAccessPoint('mon0','test',bpffilter='Dot11Deauth')
ap.run()
it gives me a no such attribute bpffilter
what am I doing wrong here? Also, even if I do specify a filter, will this mean that the AP will ignore such packets or accept them but not record them?

**Comment by rpp0** [comment]
Seems that I forgot to assign the attribute, I've pushed a fix just now. If you pull the latest version you should be able to set the bpffilter. For writing a filter, you should read http://www.tcpdump.org/manpages/pcap-filter.7.html. Filtered packets will be completely ignored at hardware level.

**Comment by localtracker** [comment]
Oh great, I thought it was me who wasn't doing something right, shud've cross checked with the code. 
Ok so then lets say I use the filter argument, bprffilter='type mgt subtype deauth' , then would the access point be rejecting any and all deauth packets sent to it ? In the scenario of a WLAN did attack, the ap would reject the packets but the client wont be able to and hence disconcert anyways, right?

**Comment by localtracker** [comment]
Oh great, I thought it was me who wasn't doing something right, shud've cross checked with the code. 
Ok so then lets say I use the filter argument, bprffilter='type mgt subtype deauth' , then would the access point be rejecting any and all deauth packets sent to it ? In the scenario of a WLAN did attack, the ap would reject the packets but the client wont be able to and hence disconcert anyways, right?

**Comment by localtracker** [comment]
I meant to write bpffilter but my phone autocorrected it.. :P

**Comment by localtracker** [comment]
I meant to write bpffilter but my phone autocorrected it.. :P

**Comment by rpp0** [comment]
No, that would only pass deauth frames. You can use the "not" keyword to invert the filter.

**Comment by localtracker** [comment]
ok so I've setup the fakeap now.. and a script that I have for detecting deauth packets is setup on the 'fakeap' interface.. When I am sending deauth commands to the interface, my script is not detecting any deauth packets which leads me to believe that the packets are being dropped.. Now the next question, although the AP cant see the packets but the client connected to the ap does get disconnected. How would I stop that?
Also, when I try to connect to the AP from my phone, it keeps showing that it is trying to connect but never does. I am running the ap as is. Can I connect the fakeap interface to eth0 using brctl?

**Comment by rpp0** [comment]
That's strange, your client shouldn't accept frames which aren't destined for its MAC address. As for the dhcp issue: I recommend that you use dnsmasq bound to the fakeap interface.
