### ISSUE TITLE
Cannot start dhcp interface on tun interface

### ISSUE THREAD

**Issue by krishnan1159** [rpp0/scapy-fakeap#5]
Hi,

When I starting the fakeap, tun interface created successfully but I am not able start dhcp server for that interface. Root cause is mac address is not assigned when fakeap is created. When I try to assign mac address using "ip link", it throwed errors.

I am using isc-dhcp-server in ubuntu to assign ip address for the clients connecting to fakeap

Can you please help

**Comment by rpp0** [comment]
It's a tun interface, so you don't need a MAC address. What seems to be the problem is that something changed in Scapy causing it to error at line 281 in callbacks.py. If you need a quick fix you can replace Raw(ip_packet) by str(ip_packet) and it should work. I'll try to push a fix soon.

**Comment by krishnan1159** [comment]
Hi, I am getting this error when trying to start dhcp server on fakeap

Unsupported device type 65534 for "fakeap"

dhcp command i used : dhcpd -d -f -cf /etc/dhcp3/dhcpd.conf fakeap

dhcp conf file ::
ddns-update-style ad-hoc;
default-lease-time 600;
max-lease-time 7200;
authoritative;
subnet 10.0.0.0 netmask 255.255.255.0 {
option subnet-mask 255.255.255.0;
option broadcast-address 10.0.0.255;
option routers 10.0.0.254;
option domain-name-servers 8.8.8.8;
range 10.0.0.1 10.0.0.140;
}

**Comment by rpp0** [comment]
Thanks for reporting the error. Can you try to use "dnsmasq" and see if that works? This is the tool that I use as DHCP server.

**Comment by rpp0** [comment]
Pushed upstream now in 760015bfed237eb12c33ce66b8166fe0644adaf4, can you please check to see if it works for you when using dnsmasq?
