### ISSUE TITLE
Switching to BSD / MIT?

### ISSUE THREAD

**Issue by sophron** [rpp0/scapy-fakeap#6]
Hello,

I'm the author of <a href="https://github.com/sophron/wifiphisher">wifiphisher, a tool for automated phishing attacks</a>. I'm considering replacing hostapd in our codebase with your project. There's a ticker for that <a href="https://github.com/sophron/wifiphisher/issues/128">here</a>.

Wifiphisher is released under the MIT license though while scapy-fakeap is GPLv2. This would lead to releasing all of wifiphisher's next versions under GPL. 

Do you consider switching to MIT or BSD for scapy-fakeap so we can avoid that?

Thank you,

George

**Comment by rpp0** [comment]
Hi, sure! I will change it when I get home tonight.

**Comment by rpp0** [comment]
Ok, I just changed it to 3-clause BSD. Nice project you got there by the way! A few words of caution though:

**Comment by rpp0** [comment]
Ok, I just changed it to 3-clause BSD. Nice project you got there by the way! A few words of caution though: when I created scapy-fakeap, I intended that it be used for fast manual fuzzing and packet crafting by providing some basic, default AP functionality and high configurability. I have used hostapd for Karma attacks as well, and in my opinion it is way superior in terms of performance. Scapy has the tendency to drop packets even if you disable packet dissection above the Ethernet layer. That said, feel free to use any functionality that would be of use to you, but keep this in mind :)!

**Comment by sophron** [comment]
Hi, again.

Thanks for doing this change but I'm afraid you'll have to revert back to GPL. I've done some further reading and apparently scapy uses GPL and any software linked to a library covered by GPL is considered a derived work, and thus needs to be covered by GPL as well. I'm also going to switch wifiphisher to GPL because of this.

Thank you for the heads up. I think I'll try some tests before proceeding. Have you tried dynamically using BPF-filters on the input for better performance?

**Comment by rpp0** [comment]
Ok, I just reverted back :). I tried static BPF filters, but not dynamically changing them. Even with dynamic BPF filters I think scapy will be too slow for practical use, but maybe they improved the performance so it's worth trying anyway.

**Comment by sophron** [comment]
Alright, I'll let you know how it goes. :)

Thanks again,

George
