### ISSUE TITLE
what's the use of get_radiotap_header ?

### ISSUE THREAD

**Issue by mohitrajain** [rpp0/scapy-fakeap#9]
Radio_tap_header is gnerated by the receiver wireless card . I tried this function and found no use . Infact the reciever wireless card recieves the radio_tap_header according to properties of the sender wireless card like channel , transmission rate etc . Please explain the use of get_radiotap_header and correct me if i am wrong ?

**Comment by rpp0** [comment]
`get_radiotap_header` is only used when _transmitting_ frames with `scapy-fakeap`. In monitor mode, you need to supply a RadioTap header so the wireless card knows what configuration to use when injecting packets. Current, `get_radiotap_header` provides a hardcoded RadioTap header with some default settings such as a rate that is supported by most cards.

**Comment by mohitrajain** [comment]
Thanks for reply . I got it now . But frequency does not change if i use get_radiotap_header for my adapter . Although i am able to control data rate of my adapter using get_radiotap_header per packet . Can you tell me why it is not working for network card ?
